@RegistrationAndAuthorisationViaCookieMinimalAPI_HostAddress = http://localhost:5118

GET {{RegistrationAndAuthorisationViaCookieMinimalAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
